version: '3.1'

services:
  telegram:
    build:
      context: .
    container_name: tg_server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TG_TOKEN=Your Token
      - WS_PORT=8080
      - WS_HOST=0.0.0.0
      - USED_BUS=internal
      - DATABASE=tgchat
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - tg-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: tg_mongodb
    volumes:
      - tg_mongodb_volume:/data/db
    restart: always
    networks:
      - tg-network

volumes:
  tg_mongodb_volume:

networks:
  tg-network:
    driver: bridge
    ipam:
      driver: default
